---
title: "drug-screening"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## R Markdown

```{r}
library(ROCR)
library(readr)
library(knitr)

# load data files
load("auc_scores.Rdata")
load("roc_results.Rdata")

# create an AUC score table
kable(auc_scores)

# plot combined ROC curves for death phenotypes
p2_roc <- performance(prediction.obj = roc_results$P2, 
                      measure = "tpr", x.measure = "fpr")
p7_roc <- performance(prediction.obj = roc_results$P7, 
                      measure = "tpr", x.measure = "fpr")
p8_roc <- performance(prediction.obj = roc_results$P8, 
                      measure = "tpr", x.measure = "fpr")
p11_roc <- performance(prediction.obj = roc_results$P11, 
                      measure = "tpr", x.measure = "fpr")
p12_roc <- performance(prediction.obj = roc_results$P12, 
                      measure = "tpr", x.measure = "fpr")
p13_roc <- performance(prediction.obj = roc_results$P13, 
                      measure = "tpr", x.measure = "fpr")
p14_roc <- performance(prediction.obj = roc_results$P14, 
                      measure = "tpr", x.measure = "fpr")


plot(p2_roc, col = "red", main = "ROC Curves For Death Indicator Phenotypes")
plot(p7_roc, col = "blue", add = TRUE)
plot(p8_roc, col = "green", add = TRUE)
plot(p11_roc, col = "black", add = TRUE)
plot(p12_roc, col = "purple", add = TRUE)
plot(p13_roc, col = "yellow", add = TRUE)
plot(p14_roc, col = "brown", add = TRUE)
legend('bottomright', c("P2", "P7", "P8", "P11", "P12", "P13", "P14"),
       lty = c(1, 1, 1, 1, 1, 1, 1), 
       lwd = c(2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5),
       col = c("red", "blue", "green", "black", "purple", "yellow", "brown"))

# precision recall plot for death phenotypes
p2_pr <- performance(prediction.obj = roc_results$P2, 
                      measure = "prec", x.measure = "rec")
p7_pr <- performance(prediction.obj = roc_results$P7, 
                      measure = "prec", x.measure = "rec")
p8_pr <- performance(prediction.obj = roc_results$P8, 
                      measure = "prec", x.measure = "rec")
p11_pr <- performance(prediction.obj = roc_results$P11, 
                      measure = "prec", x.measure = "rec")
p12_pr <- performance(prediction.obj = roc_results$P12, 
                      measure = "prec", x.measure = "rec")
p13_pr <- performance(prediction.obj = roc_results$P13, 
                      measure = "prec", x.measure = "rec")
p14_pr <- performance(prediction.obj = roc_results$P14, 
                      measure = "prec", x.measure = "rec")
plot(p2_pr, col = "red", 
     main = "Precision Recall Curves for Death Indicator Phenotypes")
plot(p7_pr, col = "blue", add = TRUE)
plot(p8_pr, col = "green", add = TRUE)
plot(p11_pr, col = "black", add = TRUE)
plot(p12_pr, col = "purple", add = TRUE)
plot(p13_pr, col = "yellow", add = TRUE)
plot(p14_pr, col = "brown", add = TRUE)
legend('bottomright', c("P2", "P7", "P8", "P11", "P12", "P13", "P14"),
       lty = c(1, 1, 1, 1, 1, 1, 1), 
       lwd = c(2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5),
       col = c("red", "blue", "green", "black", "purple", "yellow", "brown"))

```

